runtime: python
env: flex
entrypoint: gunicorn -b :$PORT server:app

runtime_config:
  python_version: 3

env_variables:
  ENV_TYPE: <Dev or Prod>
  DB_CONNECTION: <database connection string>
  DB_NAME: <database name>

beta_settings:
    cloud_sql_instances: <instance connection name>
